### ISSUE TITLE
call of overloaded 'Vector2D(<brace-enclosed initializer list>)' is ambiguous

### ISSUE THREAD

**Issue by m-tosch** [m-tosch/mu#49]
```cpp
mu::Vector2D<int> b{2, 2};   // fine. compiles
mu::Vector2D<int> c{{2, 2}}; // error
```

probably what happens is that both the variadic template constructor that takes a variable list of arguments AND the std::array constructor would be candidates to execute this code. Hence the ambiguity

Is the std::array constructor still needed at all? maybe the variadic template constructor can cover all use cases

**Comment by m-tosch** [comment]
## NOTE
With `Vector` this works just fine
```cpp
mu::Vector<2, int> d{2, 2};   // variadic template constructor
mu::Vector<2, int> e{{2, 2}}; // std::array constructor
```

**Comment by m-tosch** [comment]
NOTE 2 
The following code compiles with clang 10 but not with gcc 9.3
```cpp
mu::Vector<2, int> b{2, 2};
mu::Vector<2, int> c{{2, 2}};
mu::Vector2D<int> d{2, 2};
mu::Vector2D<int> e{{2, 2}}; // gcc error call is ambiguous
```

**Comment by m-tosch** [comment]
Full error message
```txt
/workspaces/mu/tests/test_vector2d.cpp:47:21: error: call of overloaded 'Vector2D(<brace-enclosed initializer list>)' is ambiguous
   47 |   mu::Vector2D<int> e{{2, 2}};
      |                     ^
In file included from /workspaces/mu/tests/test_vector2d.cpp:3:
/workspaces/mu/include/mu/vector.h:96:12: note: candidate: 'mu::Vector<N, T>::Vector(const std::array<T, N>&) [with long unsigned int N = 2; T = int]'
   96 |   explicit Vector(const std::array<T, N> &arr) : data_(arr) {}
      |            ^~~~~~
In file included from /workspaces/mu/tests/test_vector2d.cpp:4:
/workspaces/mu/include/mu/vector2d.h:18:23: note:   inherited here
   18 |   using Vector<2, T>::Vector;
      |                       ^~~~~~
/workspaces/mu/include/mu/vector2d.h:29:3: note: candidate: 'mu::Vector2D<T>::Vector2D(const mu::Vector<2, T>&) [with T = int]'
   29 |   Vector2D(const Vector<2, T>& other) : Vector<2, T>(other) {}
      |   ^~~~~~~~
```
Somehow the constructor in Vector2D that takes a parent object
```cpp
Vector2D(const Vector<2, T>& other) : Vector<2, T>(other) {}
```
is eligable to also take a bace-enclosed initializer list. How??

**Comment by m-tosch** [comment]
## Solution
The variadic template constructor in `Vector` was inteferring... again... the error message does not state this clearly. probably because inheritance.

Made it explicit
```cpp
template <typename... TArgs,
            std::enable_if_t<
                sizeof...(TArgs) == N &&
                    (std::is_same_v<T, std::remove_reference_t<TArgs>> && ...),
                int> = 0>
  explicit Vector(TArgs &&... args) : data_{std::forward<TArgs>(args)...} {}  // <-- explicit
```
kept all the other code as it is.

**Comment by m-tosch** [comment]
## side effect
making the constructor `explicit` prevents copy-initialization
see 52 for follow up
